# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings & SEO settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: KC Features
email: kasey@kcfeatures.com
description: > # this means to ignore newlines until "baseurl:"
  Photography, Videography, and Web Design in Spokane, WA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kcfeatures.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kculmback
author: kaseyculmback
logo: 
social: 
  name: Kasey Culmback
  links:
    - https://instagram.com/kculmback
    - https://github.com/kculmback
    - https://linkedin.com/in/kculmback

# Build settings
markdown: kramdown
gems: 
  - "jekyll-sitemap"
  - "jekyll-paginate"
  - "jekyll-seo-tag"

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "bower.json"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"

# Conversion
incremental:      true

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]



    
